name: Nuggetz Push
on:
  push:
    branches:
      - '*'
      - '!site'
jobs:
  Build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Nuggetz build on `push` started"
      - run: echo "building on branch ${{ github.ref }}"
      - run: echo "ðŸ’¡ The ${{ github.ref }} of ${{ github.repository }} repository has been cloned to the runner"
      - name: Building website
        run: cp ./src/* ./public
      - name: Commiting website to `site` branch
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git add .
          git commit -am "Nuggetz build"
          git push --force origin +site
      - name: Build complete
        run: echo "Build status is ${{ job.status }}"